import  { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Apple iphone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children}) {
  return (
    <html lang="en" className="bg-black text-slate-100">
      <body className={urbanist.className}>{children}</body>
    </html>
  );
}
